### ISSUE TITLE
Update README file.

### ISSUE THREAD

**Issue by HerbertHomolka1** [HYF-Class20/workflows-group2-intro#1]
- Setup: GitHub
    - [ ] created this issue
    - [ ]  assigned to all coaches
    - [ ] moved the issue to the project board
    - [ ] Setup: local
    - [ ]  pulled the most recent code from main/master using command git pull
    - [ ] run npm install
    - [ ] created a new branch update-readme for my introduction (name => member's name)
- Writing the content:
- update README.md
- Before pushing my branch:
     - [ ] formatted the code by running code quality check
     - [ ] fixed all linting mistakes by running code quality check
     - [ ]  Added the file into staging area
     - [ ] Added a meaningful commit message
     - [ ] pulled the most recent code from main/master using command git pull origin main or git pull origin master
     - [ ] solved conflicts if exists
- After pushing my branch:
     - [ ] created a new PR linked to this issue
     - [ ] added md label
     - [ ] make sure all of the checks passed
     - [ ] assigned someone to review and merge my PR

**Comment by talmurshidi** [comment]
The issue without details.
The issue must be with full details.

**Comment by samirm00** [comment]
Why is your `deliverables` issue not in the `home` repo ??

**Comment by amanuel-zemikael** [comment]
Still working on it
